/****** Script for SelectTopNRows command from SSMS  ******/
SELECT TOP (100) [CustomerKey]
      --,[GeographyKey]
      --,[CustomerAlternateKey]
      --,[Title]
      ,[FirstName]
      --,[MiddleName]
      ,[LastName]
      --,[NameStyle]
     -- ,[BirthDate]
     -- ,[MaritalStatus]
      --,[Suffix]
      --,[Gender]
     -- ,[EmailAddress]
      ,[YearlyIncome]
    --  ,[TotalChildren]
      --,[NumberChildrenAtHome]
      --,[EnglishEducation]
     -- ,[SpanishEducation]
     -- ,[FrenchEducation]
     -- ,[EnglishOccupation]
     -- ,[SpanishOccupation]
     -- ,[FrenchOccupation]
     -- ,[HouseOwnerFlag]
      --,[NumberCarsOwned]
      --,[AddressLine1]
     -- ,[AddressLine2]
    --  ,[Phone]
     -- ,[DateFirstPurchase]
     -- ,[CommuteDistance]
  FROM [AdventureWorksDW2019].[dbo].[DimCustomer]
  ORDER BY 
	
	FirstName ASC;